// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: bar/bar.proto

package bar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BarClient is the client API for Bar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BarClient interface {
	DoBar(ctx context.Context, in *BarReq, opts ...grpc.CallOption) (*BarResp, error)
}

type barClient struct {
	cc grpc.ClientConnInterface
}

func NewBarClient(cc grpc.ClientConnInterface) BarClient {
	return &barClient{cc}
}

func (c *barClient) DoBar(ctx context.Context, in *BarReq, opts ...grpc.CallOption) (*BarResp, error) {
	out := new(BarResp)
	err := c.cc.Invoke(ctx, "/bar.Bar/DoBar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BarServer is the server API for Bar service.
// All implementations must embed UnimplementedBarServer
// for forward compatibility
type BarServer interface {
	DoBar(context.Context, *BarReq) (*BarResp, error)
	mustEmbedUnimplementedBarServer()
}

// UnimplementedBarServer must be embedded to have forward compatible implementations.
type UnimplementedBarServer struct {
}

func (UnimplementedBarServer) DoBar(context.Context, *BarReq) (*BarResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoBar not implemented")
}
func (UnimplementedBarServer) mustEmbedUnimplementedBarServer() {}

// UnsafeBarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BarServer will
// result in compilation errors.
type UnsafeBarServer interface {
	mustEmbedUnimplementedBarServer()
}

func RegisterBarServer(s grpc.ServiceRegistrar, srv BarServer) {
	s.RegisterService(&Bar_ServiceDesc, srv)
}

func _Bar_DoBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarServer).DoBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bar.Bar/DoBar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarServer).DoBar(ctx, req.(*BarReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Bar_ServiceDesc is the grpc.ServiceDesc for Bar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bar.Bar",
	HandlerType: (*BarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoBar",
			Handler:    _Bar_DoBar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bar/bar.proto",
}
